// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

= Entwickler/innen/handbuch
Gruppe 4, Jens Ettl, Ines Rodrigues, Joschua Schuhmacher, Amandus von Bornhaupt
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

Auf den Nest Applikatonsserver kann über die zwei Schnittstellen, REST und GraphQL, zugegriffen werden. Der Datenbankserver basiert auf MongoDB.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

Ist REST eine API?
REST- (Representational State Transfer) bzw. RESTful-API ist ein Application-Program-Interface-Typ (API-Typ), 
der webbasierte Apps in der Kommunikation miteinander unterstützt. Hierfür werden die HTTP-Methoden GET,POST,PUT,PATCH,DELETE genutzt.

.Controller für die REST-Schnittstelle
[plantuml,AutoController,svg]
----
include::AutoController.puml[]
----

=== Die GraphQL-Schnittstelle

GraphQL ist eine Abfragesprache und serverseitige Laufzeitumgebung für Anwendungsprogrammierschnittstellen (APIs), 
die es sich zur Aufgabe gemacht hat, den Kunden genau die Daten zu liefern, die sie anfordern, und nicht mehr. - RedHat

Eine mögliche Abfrage wäre zum Beispiel:
query ExampleQuery {
  autos {
    id
    verbrauch
    marke
    preis
  } 
}

.Resolver für die GraphQL-Schnittstelle
[plantuml,AutoResolver,svg]
----
include::AutoResolver.puml[]
----

=== Der Anwendungskern

.Anwendungskern
[plantuml,AutoService,svg]
----
include::AutoService.puml[]
----

=== Klasse für Entities und MongoDB-Dokumente

.Entity und Document
[plantuml,Auto,svg]
----
include::Auto.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Google_:: https://google.github.io/styleguide/tsguide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
